// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week2.Data;

#nullable disable

namespace Week2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Week2.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Carly Reid",
                            CategoryId = 1,
                            Cover = "images/book1.jpg",
                            Price = 2.5,
                            PublishYear = 2023,
                            Title = "Death in the Clan"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Henry Gray",
                            CategoryId = 4,
                            Cover = "images/medical1.jpg",
                            Price = 89.989999999999995,
                            PublishYear = 2020,
                            Title = "Gray's Anatomy"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J. Larry Jameson",
                            CategoryId = 4,
                            Cover = "images/medical2.jpg",
                            Price = 149.99000000000001,
                            PublishYear = 2022,
                            Title = "Harrison's Principles of Internal Medicine"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Vinay Kumar",
                            CategoryId = 4,
                            Cover = "images/medical3.jpg",
                            Price = 79.989999999999995,
                            PublishYear = 2021,
                            Title = "Robbins Basic Pathology"
                        },
                        new
                        {
                            Id = 5,
                            Author = "John E. Hall",
                            CategoryId = 4,
                            Cover = "images/medical4.jpg",
                            Price = 94.989999999999995,
                            PublishYear = 2021,
                            Title = "Guyton and Hall Textbook of Medical Physiology"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Morris J. Brown",
                            CategoryId = 4,
                            Cover = "images/medical5.jpg",
                            Price = 69.989999999999995,
                            PublishYear = 2019,
                            Title = "Clinical Pharmacology"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Stuart H. Ralston",
                            CategoryId = 4,
                            Cover = "images/medical6.jpg",
                            Price = 84.989999999999995,
                            PublishYear = 2022,
                            Title = "Davidson's Principles and Practice of Medicine"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Frank H. Netter",
                            CategoryId = 4,
                            Cover = "images/medical7.jpg",
                            Price = 74.989999999999995,
                            PublishYear = 2019,
                            Title = "Netter's Atlas of Human Anatomy"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Ian B. Wilkinson",
                            CategoryId = 4,
                            Cover = "images/medical8.jpg",
                            Price = 49.990000000000002,
                            PublishYear = 2020,
                            Title = "Oxford Handbook of Clinical Medicine"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Parveen Kumar",
                            CategoryId = 4,
                            Cover = "images/medical9.jpg",
                            Price = 89.989999999999995,
                            PublishYear = 2021,
                            Title = "Kumar and Clark's Clinical Medicine"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Carol D. Tamparo",
                            CategoryId = 4,
                            Cover = "images/medical10.jpg",
                            Price = 64.989999999999995,
                            PublishYear = 2022,
                            Title = "Diseases of the Human Body"
                        });
                });

            modelBuilder.Entity("Week2.Models.BookImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");
                });

            modelBuilder.Entity("Week2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Medical"
                        });
                });

            modelBuilder.Entity("Week2.Models.Book", b =>
                {
                    b.HasOne("Week2.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Week2.Models.BookImages", b =>
                {
                    b.HasOne("Week2.Models.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Week2.Models.Book", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Week2.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
